### ISSUE TITLE
Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by sirousjj** [CTK-WARRIOR/instagram-autopost-bot#2]
hi dear.
i got this error : 

instagram-autopost-bot-master\node_modules\instagram-web-api\lib\index.js:109
        html => html.split('window._sharedData = ')[1].split(';</script>')[0]
                                                      ^

TypeError: Cannot read properties of undefined (reading 'split')

what should i do?

**Comment by pal404blog** [comment]
> hi dear. i got this error :
> 
> instagram-autopost-bot-master\node_modules\instagram-web-api\lib\index.js:109 html => html.split('window._sharedData = ')[1].split(';</script>')[0] ^
> 
> TypeError: Cannot read properties of undefined (reading 'split')
> 
> what should i do?

same problem

**Comment by sirousjj** [comment]
I solve this error with this solution:
in this file :
node_modules\instagram-web-api\lib\index.js
in line 109
put _sharedData =false 
and save and deploy again the project
